Public Class SessionType

    Public Const DelExpImg As String = "DelExpImg"
    Public Const DelExpAttachImg As String = "DelExpAttachImg"
    Public Const DelExpActionImg As String = "DelExpActionImg"
    Public Const AddExpImg As String = "AddExpImg"
    Public Const AddExpAttachImg As String = "AddExpAttachImg"
    Public Const AddExpActionImg As String = "AddExpActionImg"
    Public Const DelExpDenote As String = "DelExpDenote"
    Public Const DelExpAttach As String = "DelExpAttach"
    Public Const AddExpDenote As String = "AddExpDenote"
    Public Const AddExpAction As String = "AddExpAction"
    Public Const AddExpAttach As String = "AddExpAttach"
    Public Const FollowExp As String = "FollowExp"
    Public Const DelExp As String = "DelExp"
    Public Const EditExp As String = "EditExp"
    Public Const NewExp As String = "NewExp"
    Public Const DelImpImg As String = "DelImpImg"
    Public Const DelImpAttachImg As String = "DelImpAttachImg"
    Public Const DelImpActionImg As String = "DelImpActionImg"
    Public Const AddImpImg As String = "AddImpImg"
    Public Const AddImpAttachImg As String = "AddImpAttachImg"
    Public Const AddImpActionImg As String = "AddImpActionImg"
    Public Const DelImpDenote As String = "DelImpDenote"
    Public Const DelImpAction As String = "DelImpAction"
    Public Const DelImpAttach As String = "DelImpAttach"
    Public Const AddImpDenote As String = "AddImpDenote"
    Public Const AddImpAction As String = "AddImpAction"
    Public Const AddImpAttach As String = "AddImpAttach"
    Public Const FollowImp As String = "FollowImp"
    Public Const DelImp As String = "DelImp"
    Public Const EditImp As String = "EditImp"
    Public Const NewImp As String = "NewImp"
    Public Const PrintReport As String = "PrintReport"
    Public Const OpenReport As String = "OpenReport"
    Public Const Logout As String = "Logout"
    Public Const Login As String = "Login"
    Public Const DelImpFolder As String = "DelImpImg"
    Public Const DelExpFolder As String = "DelImpImg"
    Public Const DelExpAction As String = "DelExpAction"

End Class
